// app/login/page.tsx
"use client"

import type React from "react"

import { useState } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Camera, Users, ArrowLeft, Shield } from "lucide-react"
import { GlitterBackground } from "@/components/glitter-background"

export default function LoginPage() {
  const [formData, setFormData] = useState({
    email: "",
    password: "",
    mfaCode: "",
  })
  const [showMFA, setShowMFA] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [currentUserType, setCurrentUserType] = useState("")
  const [error, setError] = useState("")

  const handleSubmit = async (e: React.FormEvent, userType: string) => {
    e.preventDefault()
    setIsLoading(true)
    setError("")
    setCurrentUserType(userType)

    try {
      const response = await fetch("/api/auth/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email: formData.email,
          password: formData.password,
          userType: userType,
          mfaCode: showMFA ? formData.mfaCode : null,
        }),
      })

      const responseText = await response.text()
      console.log("Response status:", response.status)
      console.log("Response text:", responseText)

      if (!response.ok) {
        let errorMessage = "Login failed"
        try {
          const errorData = JSON.parse(responseText)
          errorMessage = errorData.error || errorMessage
        } catch {
          errorMessage = `Server error (${response.status})`
        }
        setError(errorMessage)
        setIsLoading(false)
        return
      }

      let data
      try {
        data = JSON.parse(responseText)
      } catch (parseError) {
        console.error("JSON parse error:", parseError)
        setError("Invalid server response")
        setIsLoading(false)
        return
      }

      if (data.requiresMFA && !showMFA) {
        setShowMFA(true)
        setIsLoading(false)
      } else {
        // Login successful
        if (userType === "client") {
          window.location.href = "/client/dashboard"
        } else {
          window.location.href = "/photographer/dashboard"
        }
      }
    } catch (error) {
      console.error("Login error:", error)
      setError("Network error. Please try again.")
      setIsLoading(false)
    }
  }

  const resetForm = () => {
    setShowMFA(false)
    setFormData({ email: "", password: "", mfaCode: "" })
    setCurrentUserType("")
    setError("")
  }

  return (
    <div className="min-h-screen relative">
      <GlitterBackground />
      <div className="relative z-10 flex items-center justify-center p-4">
        <div className="w-full max-w-md">
          <div className="mb-6">
            <Link href="/" className="inline-flex items-center text-blue-600 hover:text-blue-800">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Home
            </Link>
          </div>

          <Card className="bg-white/95 backdrop-blur-sm">
            <CardHeader className="text-center">
              <CardTitle className="text-2xl">Welcome Back</CardTitle>
              <CardDescription>Sign in to your ClickHire account</CardDescription>
            </CardHeader>

            <CardContent>
              {error && (
                <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-md">
                  <p className="text-sm text-red-600">{error}</p>
                </div>
              )}

              {!showMFA ? (
                <Tabs defaultValue="client" className="w-full">
                  <TabsList className="grid w-full grid-cols-2">
                    <TabsTrigger value="client" className="flex items-center space-x-2">
                      <Users className="h-4 w-4" />
                      <span>Client</span>
                    </TabsTrigger>
                    <TabsTrigger value="photographer" className="flex items-center space-x-2">
                      <Camera className="h-4 w-4" />
                      <span>Photographer</span>
                    </TabsTrigger>
                  </TabsList>

                  <TabsContent value="client">
                    <form onSubmit={(e) => handleSubmit(e, "client")} className="space-y-4">
                      <div className="space-y-2">
                        <Label htmlFor="client-email">Email</Label>
                        <Input
                          id="client-email"
                          type="email"
                          value={formData.email}
                          onChange={(e) => setFormData((prev) => ({ ...prev, email: e.target.value }))}
                          required
                          disabled={isLoading}
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="client-password">Password</Label>
                        <Input
                          id="client-password"
                          type="password"
                          value={formData.password}
                          onChange={(e) => setFormData((prev) => ({ ...prev, password: e.target.value }))}
                          required
                          disabled={isLoading}
                        />
                      </div>

                      <Button type="submit" className="w-full" disabled={isLoading}>
                        {isLoading ? "Signing In..." : "Continue"}
                      </Button>
                    </form>
                  </TabsContent>

                  <TabsContent value="photographer">
                    <form onSubmit={(e) => handleSubmit(e, "photographer")} className="space-y-4">
                      <div className="space-y-2">
                        <Label htmlFor="photographer-email">Email</Label>
                        <Input
                          id="photographer-email"
                          type="email"
                          value={formData.email}
                          onChange={(e) => setFormData((prev) => ({ ...prev, email: e.target.value }))}
                          required
                          disabled={isLoading}
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="photographer-password">Password</Label>
                        <Input
                          id="photographer-password"
                          type="password"
                          value={formData.password}
                          onChange={(e) => setFormData((prev) => ({ ...prev, password: e.target.value }))}
                          required
                          disabled={isLoading}
                        />
                      </div>

                      <Button type="submit" className="w-full bg-green-600 hover:bg-green-700" disabled={isLoading}>
                        {isLoading ? "Signing In..." : "Continue"}
                      </Button>
                    </form>
                  </TabsContent>
                </Tabs>
              ) : (
                <div className="space-y-4">
                  <div className="flex items-center space-x-2 p-4 bg-blue-50 rounded-md">
                    <Shield className="h-5 w-5 text-blue-600" />
                    <div>
                      <p className="text-sm font-medium">Multi-Factor Authentication</p>
                      <p className="text-xs text-gray-600">Enter any 6-digit code (demo mode)</p>
                    </div>
                  </div>

                  <form onSubmit={(e) => handleSubmit(e, currentUserType)} className="space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="mfa-code">Authentication Code</Label>
                      <Input
                        id="mfa-code"
                        value={formData.mfaCode}
                        onChange={(e) => setFormData((prev) => ({ ...prev, mfaCode: e.target.value }))}
                        placeholder="Enter 6-digit code (e.g., 123456)"
                        maxLength={6}
                        required
                        disabled={isLoading}
                      />
                    </div>

                    <div className="flex space-x-2">
                      <Button
                        type="button"
                        variant="outline"
                        onClick={resetForm}
                        className="flex-1"
                        disabled={isLoading}
                      >
                        Back
                      </Button>
                      <Button
                        type="submit"
                        className={`flex-1 ${
                          currentUserType === "photographer" ? "bg-green-600 hover:bg-green-700" : ""
                        }`}
                        disabled={isLoading}
                      >
                        {isLoading ? "Verifying..." : "Verify & Sign In"}
                      </Button>
                    </div>
                  </form>
                </div>
              )}

              <div className="mt-6 text-center text-sm text-gray-600">
                Don't have an account?{" "}
                <Link href="/register" className="text-blue-600 hover:underline">
                  Sign up here
                </Link>
              </div>

              {/* Demo credentials helper */}
              <div className="mt-4 p-3 bg-gray-50 rounded-md">
                <p className="text-xs text-gray-600 font-medium mb-2">Demo Credentials:</p>
                <div className="space-y-1">
                  <p className="text-xs text-gray-600">📧 sarah.johnson@example.com (Photographer)</p>
                  <p className="text-xs text-gray-600">📧 john.client@example.com (Client)</p>
                  <p className="text-xs text-gray-600">🔑 Password: password123</p>
                  <p className="text-xs text-gray-600">🔐 MFA: Any 6-digit code (e.g., 123456)</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

// clickhire-frontend/src/routes/login/+page.svelte
<script lang="ts">
    import { goto } from '$app/navigation';
    import { user } from '$lib/stores/authStore';
    import SectionTitle from '$components/app/SectionTitle.svelte';
    import Input from '$components/ui/Input.svelte';
    import Button from '$components/ui/Button.svelte';
    import ErrorMessage from '$components/ui/ErrorMessage.svelte';
    import type { User } from '$lib/stores/authStore';

    let email = '';
    let password = '';
    let isLoading = false;
    let errorMessage: string | null = null;

    async function handleSubmit() {
        errorMessage = null;
        isLoading = true;

        try {
            // In a real app, this would be an API call to your backend
            const response = await new Promise<Response>(resolve => setTimeout(() => {
                if (email === 'client@example.com' && password === 'password') {
                    resolve(new Response(JSON.stringify({
                        message: 'Login successful.',
                        token: 'mock-client-token',
                        user: { id: 'c1', name: 'Emily Brown', role: 'client', email: 'client@example.com' } as User
                    }), { status: 200, headers: { 'Content-Type': 'application/json' } }));
                } else if (email === 'photog@example.com' && password === 'password') {
                    resolve(new Response(JSON.stringify({
                        message: 'Login successful.',
                        token: 'mock-photog-token',
                        user: { id: 'p1', name: 'Alice Smith', role: 'photographer', email: 'photog@example.com' } as User
                    }), { status: 200, headers: { 'Content-Type': 'application/json' } }));
                } else {
                    resolve(new Response(JSON.stringify({ message: 'Invalid credentials.' }), { status: 401, headers: { 'Content-Type': 'application/json' } }));
                }
            }, 1000));

            const data = await response.json();

            if (response.ok) {
                user.set(data.user);
                if (data.user.role === 'client') {
                    goto('/client/dashboard');
                } else {
                    goto('/photographer/dashboard');
                }
            } else {
                errorMessage = data.message;
            }
        } catch (error: any) {
            console.error('Login error:', error);
            errorMessage = 'An unexpected error occurred: ' + error.message;
        } finally {
            isLoading = false;
        }
    }
</script>

<div class="max-w-md mx-auto bg-gray-800 p-8 rounded-lg shadow-lg text-white mt-10">
    <SectionTitle title="Login to ClickHire" subtitle="Access your client or photographer account." />

    <form on:submit|preventDefault={handleSubmit} class="space-y-4">
        <div>
            <label for="email" class="block text-sm font-medium mb-1">Email</label>
            <Input id="email" type="email" bind:value={email} required />
        </div>
        <div>
            <label for="password" class="block text-sm font-medium mb-1">Password</label>
            <Input id="password" type="password" bind:value={password} required />
        </div>

        <ErrorMessage message={errorMessage} />

        <Button type="submit" disabled={isLoading} class="w-full">
            {#if isLoading}
                Logging in...
            {:else}
                Login
            {/if}
        </Button>
    </form>

    <p class="text-center text-sm text-gray-400 mt-4">
        Don't have an account? <a href="/signup" class="text-primary-blue hover:underline">Register here</a>
    </p>
</div>
